apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-web
spec:
  selector:
    matchLabels:
      app: financial-web
  template:
    metadata:
      labels:
        app: financial-web
    spec:
      containers:
      - name: financial-web
        image: echenim007/financial-web:latest
        ports:
        - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: financial-web
spec:
  selector:
    app: financial-web
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
  type: LoadBalancer


