apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-tech
spec:
  selector:
    matchLabels:
      app: fin-tech
  template:
    metadata:
      labels:
        app: fin-tech
    spec:
      containers:
      - name: fin-tech
        image: echenim007/fin-tech:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: fin-tech
spec:
  selector:
    app: fin-tech
  ports:
    - protocol: TCP
      port: 8181
  type: LoadBalancer


