apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-web
spec:
  selector:
    matchLabels:
      app: distributed-web
  replicas: 2
  template:
    metadata:
      labels:
        app: distributed-web
    spec:
      containers:
      - name: distributed-web
        image: echenim007/distributed-web:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: distributed-web
spec:
  selector:
    app: distributed-web
  ports:
    - protocol: TCP
      port: 30000
  type: LoadBalancer


