apiVersion: v1
kind: Service
metadata:
  name: IBank
spec:
  selector:
    app: IBank
  ports:
  - name: IBank
    protocol: "TCP"
    port: 8181
    targetPort: 8181
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: IBank
spec:
  selector:
    matchLabels:
      app: IBank
  replicas: 2
  template:
    metadata:
      labels:
        app: IBank
    spec:
      containers:
      - name: financial-web
        image: echenim007/ibank:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8181

      

