apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed
spec:
  selector:
    matchLabels:
      app: distributed
  template:
    metadata:
      labels:
        app: distributed
    spec:
      containers:
      - name: distributed
        image: echenim007/distributed:v1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: distributed
spec:
  selector:
    app: distributed
  ports:
    - protocol: TCP
      port: 8181
  type: LoadBalancer


