apiVersion: v1
kind: Service
metadata:
  name: financial-web-service
spec:
  selector:
    app: financial-web
  ports:
  - protocol: "TCP"
    port: 8082
    targetPort: 8181
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-web
spec:
  selector:
    matchLabels:
      app: financial-web
  replicas: 3
  template:
    metadata:
      labels:
        app: financial-web
    spec:
      containers:
      - name: financial-web
        image: echenim007/financial-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8181